[package]
name = "png2mozjpegd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.4", default-features = false, features = [ "png" ] }
mozjpeg = "0.9.4"
notify = "5.0.0"
tokio = { version = "1.21.2", features = ["rt-multi-thread", "time", "macros"] , default-features = false}
serde = { version = "1.0.147" , features = ["derive"] }
serde_yaml = "0.9.14"
once_cell = "1.16.0"
walkdir = "2.3.2"
dirs = "4.0.0"
num_cpus = "1.13.1"
