[package]
name = "png2mozjpegd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.2", default-features = false, features = [ "png" ] }
mozjpeg = "0.9.3"
notify = "4.0.17"
tokio = { version = "1.20.0", features = ["rt-multi-thread", "time", "macros"] , default-features = false}
serde = { version = "1.0.139" , features = ["derive"] }
serde_yaml = "0.8.26"
once_cell = "1.13.0"
walkdir = "2.3.2"
dirs = "4.0.0"
num_cpus = "1.13.1"
