[package]
name = "image-compress-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.23", default-features = false, features = [ "png" ] }
mozjpeg = { git = "https://github.com/ImageOptim/mozjpeg-rust/" }
notify = "4"
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros"] , default-features = false}
serde = { version = "1.0" , features = ["derive"] }
serde_yaml = "0.8"
once_cell = "1.8"
walkdir = "2"
dirs = "4"
num_cpus = "1"
